### ISSUE TITLE
Unknown command "docker up"

### ISSUE THREAD

**Issue by brutalVinz** [raphaelM-sudo/ExaPi#1]
Hi raphaelM-sudo,

i want to try your project but i did not succeed to run the "docker up ."  command from your README.MD
Could you help me?

**Comment by raphaelM-sudo** [comment]
Hello,
I have updated the readme.md now.
If the build succeeded without any errors, you have already created the image.
ExaPi was meant to be used as a base image and not to be used to bash into the container.
However, you can do so by: docker run -it --entrypoint /bin/bash <IMAGE_ID>
